# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0c1cf05b125b7c09e34028af09cf4cee40498a0d75a8ebd86a8217ff464c96e20561e75e53c3da276a5cb2116684464f7da596409706ad7fb9e775664d578fd

test:
  secret_key_base: 929cb771c92c6305aeae8ccd1e767d917ed8fd4f085d8acc3163bb1cbfcd880c81ccaac073568395ae4762949b0a9b38db9f5fea00dccb82f4ae1ae86883191e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
